# Generated by Django 4.1 on 2022-09-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created', 'updated']},
        ),
    ]
